x-def-logging: &default-logging
  logging:
    # Указываем, какой драйвер использовать
    driver: "loki"
    options:
      # Адрес Loki, куда складывать логи
      # Обратите внимание, что здесь используется не имя сервиса loki, а локальный хост, на который проброшен порт Loki,
      # это сделано потому, что логи будет писать docker engine, котрый расположен на хостовой машине,
      # и он не знает имени хоста контейнера Loki, которое ему присвоил compose во внутренней сети проекта.
      loki-url: "http://localhost:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s

services:
  postgis:
    hostname: postgis
    container_name: dating-postgis
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./pgisdata:/var/lib/postgresql/data"

  redis:
    hostname: redis
    container_name: dating-redis
    image: redis:latest
    restart: always
    volumes:
      - "./redis-data:/data"

  minio:
    hostname: minio
    volumes:
      - "./data:/data"
    image: quay.io/minio/minio:RELEASE.2023-08-04T17-40-21Z
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/dating;
      /usr/bin/mc anonymous set public myminio/dating;
      exit 0;
      "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    container_name: dating-backend-app
    build: .
    env_file:
      .env
    ports:
      - "8032:8032"
    restart: always
    <<: *default-logging
    depends_on:
      - postgis
      - minio
      - redis

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      minio:
        condition: service_healthy
      app:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    volumes:
      - prometheus:/etc/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      app:
        condition: service_started

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    user: root
    restart: unless-stopped

  loki:
    hostname: loki
    image: grafana/loki:2.9.0
    environment:
      TZ: ${SYSTEM_TIMEZONE:-Europe/Moscow}
    # Мы пробросили конфигурацию в файловую систему контейнера
    volumes:
      - ./loki/retention-config.yaml:/etc/loki/retention-config.yaml
    ports:
      - "3100:3100"
    # и модифицировали команду запуска, чтобы использовалась наша конфигурация
    command: -config.file=/etc/loki/retention-config.yaml

  web-panel:
    hostname: web-panel
    image: gitlab.eagledev.ru:5050/dating/web-admin-panel
    ports:
      - 8084:80

volumes:
  pgisdata:
  redis-data:
    driver: local
  prometheus:
  grafana-storage:
